# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 264ca68acc5335f3d9f53d230e8fa56547871362c131af8cdb420829633878ed362fdf6091a5330c22d1f33de01a16cda1fbaacaa0da5621468c051f142d446a

test:
  secret_key_base: af1ed53544dcfdb749921f67fa300b28158065dd03a639e22ffb0e9db299e39f047f7ecda426521cf1bd553324ba1aaef2039872cf7ee07b9a681661c1c80444

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
